language: node_js
node_js:
  - node
services: 
  - mongodb
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-tools
before_script:
  - sleep 15
script:
  - npm test-coverage
