# Do not build on tags (GitHub and BitBucket)
skip_tags: true
# Skipping commits with particular message or from specific user
skip_commits:
  message: /Created.*\.(png|jpg|jpeg|bmp|gif)/      # Regex for matching commit message
# Maximum number of concurrent jobs for the project
max_jobs: 1

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"
  DEBUG: "true"
# Require mongodb service
services:
  - mongodb
# Install scripts. (runs after repo cloning)
install:
  # Install MongoDb server
  - set PATH=%PATH%;C:\mongodb\bin
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test
  
build: off

# create Release.zip  
deploy:
  release: telebotty-v$(appveyor_build_version)_prepacked
  description: 'Automated build with dependencies'
  provider: GitHub
  auth_token:
    secure: 5+Kn0lMBHAgctK6JlkC+pPSteugVXMKXvoxuk1P+0P/y0CVbPX1T7CF9XBIO78to
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only
